ALTER TABLE teams
ADD COLUMN boss_hp INTEGER DEFAULT 10000,
ADD COLUMN boss_max_hp INTEGER DEFAULT 10000,
ADD COLUMN boss_name TEXT DEFAULT 'The Sloth King',
ADD COLUMN boss_image_index INTEGER DEFAULT 0;
